FROM python:3.10-slim

WORKDIR /app

# Установить системные зависимости
RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    sqlite3 \
    redis-tools \
    && apt-get clean

# Установить Python-зависимости
COPY req.txt .
RUN pip install --no-cache-dir -r req.txt

# Копировать исходный код
COPY . .

# Устанавливаем рабочую директорию
CMD ["celery", "-A", "celery_service.celery_config", "worker", "--loglevel=info", "--concurrency=1"]

